### ISSUE TITLE
Client side Image maps.

### ISSUE THREAD

**Issue by jahagirdar** [ronsavage/GraphViz2#1]
From the Graphviz document at
http://www.graphviz.org/doc/info/output.html#d:cmapx

```
For client-side maps, one again generates two output files:
dot -Tcmapx -ox.map -Tgif -ox.gif x.gv
```

Dot takes two sets of format and output files one for the image and the other for the imagemap

Looking at the code of Graphviz2.pm I see that the call to run3 on line 752 takes only one format and  the output goes to STDOUT.

Is it possible to change the functionality to support multiple outputs?

**Comment by ronsavage** [comment]
Hi

On 20/10/16 01:09, Vijayvithal wrote:

> From the Graphviz document at
> http://www.graphviz.org/doc/info/output.html#d:cmapx
> 
> For client-side maps, one again generates two output files:
> dot -Tcmapx -ox.map -Tgif -ox.gif x.gv
> 
> Dot takes two sets of format and output files one for the image and the
> other for the imagemap
> 
> Looking at the code of Graphviz2.pm I see that the call to run3 on line
> 752 takes only one format and the output goes to STDOUT.
> 
> Is it possible to change the functionality to support multiple outputs?

Yes. I have a demo running, and tomorrow I'll do more checking and add 
the docs.

## 

Ron Savage - savage.net.au

**Comment by ronsavage** [comment]
GraphViz2 V 2.43 with image map support is now on CPAN.
