### ISSUE TITLE
Newer attributes not considered valid

### ISSUE THREAD

**Issue by nowthis** [ronsavage/GraphViz2#11]
Hi folks.

When trying to use the `class` attribute for a node, we receive an error that it is not a valid attribute in the 'node' context.

The attribute is valid according to Graphviz - https://graphviz.org/docs/attrs/class/

I've poked around in the GraphViz2 commit history and found a commit (f254bacd3) where 5 new items (including `class`) were added to the `data/attributes.dat` file, but they have not yet been added in the `lib/GraphViz2.pm` file (and so they are not treated as valid).

I _think_ all that's needed to add support for these new attributes is to add the same new lines to `lib/GraphViz2.pm`? (I could be wrong.)

Below is the list of lines which are present in `data/attributes.dat` and not yet added to the [`@@ common_attribute` section of GraphViz2.pm](https://github.com/graphviz-perl/GraphViz2/blob/master/lib/GraphViz2.pm#L1863):

```
_background => graph
class => edge, node, cluster, graph
imagepos => node
newrank => graph
notranslate => graph
```
Could these newer attributes be added?
If it would help, I can put together a pull request adding these lines to the module file.

Thanks for your work on this module.

**Comment by mohawk2** [comment]
A pull request would be most welcome! Please also run `scripts/extract.attributes.pl` first just to make sure there are no extra attributes that have crept it.

**Comment by nowthis** [comment]
Will do. Thanks.

Looks like there will be 1 arrow shape and 2 node shapes to add as well.
