### ISSUE TITLE
Please support to choose layout

### ISSUE THREAD

**Issue by BlueEye0609** [ronsavage/GraphViz2#13]
1. we used to use GraphViz. but now the GraphViz is gone in cpan and we can't build image with the old GraphViz. could you please enable it again?
2. the new GraphViz2 seems doesnt support choose layout. https://github.com/graphviz-perl/GraphViz2/blob/master/lib/GraphViz2.pm#L559 here it only support to choose the format. but run without http://www.graphviz.org/doc/info/command.html#-K even though we already sent the parameter to graph.

**Comment by mohawk2** [comment]
I've just uploaded 2.25 of GraphViz, which is the same as 2.24. I don't know why it got deleted, sorry about that.

**Comment by mohawk2** [comment]
Regarding the layout, it actually is possible to select that, by giving a `driver` option to either the constructor on creation as a `global` (https://metacpan.org/pod/GraphViz2#driver-=%3E-$program_name) or to the `run` method: https://metacpan.org/pod/GraphViz2#run(%5Bdriver-=%3E-$exe,-format-=%3E-$string,-timeout-=%3E-$integer,-output_file-=%3E-$output_file%5D). It's not amazingly well-named. I've added a doc note.

**Comment by Yejing0609** [comment]
Hi, GraphViz still can't be installed via cpan
```
cpanm (App::cpanminus) 1.7046 on perl 5.024000 built for x86_64-linux
Work directory is /root/.cpanm/work/1661070867.16244
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching GraphViz () on cpanmetadb ...
--> Working on GraphViz
Fetching https://www.cpan.org/authors/id/E/ET/ETJ/GraphViz-2.25.tar.gz
-> OK
Unpacking GraphViz-2.25.tar.gz
Entering GraphViz-2.25
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.10_01)
Configuring GraphViz-2.25
Running Makefile.PL
Can't exec "dot": No such file or directory at Makefile.PL line 21.
Please install Graphviz from http://www.graphviz.org/.
-> N/A
! Configuring GraphViz-2.25 failed. See /root/.cpanm/work/1661070867.16244/build.log for details.
```

**Comment by ronsavage** [comment]
Hi Blue Eye

I think you meant to install GraphViz2 - not the obsolete GraphViz!

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
@ronsavage It may be obsolete, but that is not a good reason to delete it from CPAN.

**Comment by ronsavage** [comment]
Hi mohawk2

But a CPAN search returns your copy:
https://metacpan.org/dist/GraphViz2

Would there be any point in my CPAN repo hosting a copy as well?

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
You are linking to GraphViz**2**. The problem for the user was caused by you having deleted **GraphViz**. They are different distributions.

**Comment by ronsavage** [comment]
Hi

You were right. Sorry. I did not expect or even believe anyone would 
still want to download GraphViz, or even upgrade it.

To satisfy CPAN, I bumped the version # to 2.25, and updated some 
things. See Changes for details.


---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
@ronsavage I already uploaded a 2.25 as I said on 21 Aug, over two months ago, which yours now clashes with. You have pushed your changes to a `main` branch which is not the default for that repo. Please can you stop helping?

**Comment by ronsavage** [comment]
Hi

Sorry. I've set my GraphViz 2.25 for deletion from PAUSE on Friday. OK?

---
Cheers
Ron
savage.net.au

**Comment by mohawk2** [comment]
No, since it's left GraphViz entirely removed. Please actually just do nothing with CPAN going forwards without asking me first? :-)

**Comment by mohawk2** [comment]
I have uploaded yet another version (2.26) to CPAN. Here's hoping no competing versions get uploaded.
