### ISSUE TITLE
Assumption about output_file being in same folder

### ISSUE THREAD

**Issue by jahagirdar** [ronsavage/GraphViz2#2]
The code below (Line #804) assumes that the user has provided only the filename without any path information

```
        my($temp_file)  = File::Spec -> catfile($temp_dir, "$output_file.gv");
```

this results in the following error message when output_file is set to `/prj/web/public/graphs/GraphSzybt.png`

```
Can't open(> /tmp/temp.wVXt//prj/web/public/graphs/GraphSzybt.png.gv): No such file or directory at /usr/local/share/perl/5.22.1/GraphViz2.pm
```

Changing the line to 

```
my(undef,$temp_file)    = tempfile('temp.XXXX', DIR => $temp_dir, SUFFIX=>".gv");
```

and the use statement to

```
use File::Temp qw(tempfile);        # For newdir().
```

can resolve this issue.

**Comment by ronsavage** [comment]
You're right. V 2.44 is now on CPAN.
